# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .hello_world import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "hello-pulumi-go",
  "mod": "index",
  "fqn": "pulumi_hello_pulumi_go",
  "classes": {
   "hello-pulumi-go:index:HelloWorld": "HelloWorld"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "hello-pulumi-go",
  "token": "pulumi:providers:hello-pulumi-go",
  "fqn": "pulumi_hello_pulumi_go",
  "class": "Provider"
 }
]
"""
)
