// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.hellopulumigo;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.hellopulumigo.HelloWorldArgs;
import com.pulumi.hellopulumigo.Utilities;
import java.lang.Boolean;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="hello-pulumi-go:index:HelloWorld")
public class HelloWorld extends com.pulumi.resources.CustomResource {
    @Export(name="loud", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> loud;

    public Output<Optional<Boolean>> loud() {
        return Codegen.optional(this.loud);
    }
    @Export(name="message", refs={String.class}, tree="[0]")
    private Output<String> message;

    public Output<String> message() {
        return this.message;
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public HelloWorld(String name) {
        this(name, HelloWorldArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public HelloWorld(String name, HelloWorldArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public HelloWorld(String name, HelloWorldArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("hello-pulumi-go:index:HelloWorld", name, args == null ? HelloWorldArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private HelloWorld(String name, Output<String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("hello-pulumi-go:index:HelloWorld", name, null, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static HelloWorld get(String name, Output<String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new HelloWorld(name, id, options);
    }
}
